# Generated by Django 2.1.1 on 2018-09-01 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20180901_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='pracownik',
            name='foto',
            field=models.ImageField(blank=True, upload_to='pracownik/%y/%m/%d'),
        ),
    ]
