# Generated by Django 2.1.1 on 2018-09-01 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_pracownik_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pracownik',
            name='kontakt',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
