# Generated by Django 2.1.1 on 2018-09-01 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20180901_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pracownik',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
