# Generated by Django 2.1.1 on 2018-09-03 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_usluga'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galaz_prawa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Gałęzie prawa',
            },
        ),
        migrations.CreateModel(
            name='Swiadczone_uslugi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_uslugi', models.TextField()),
                ('galaz_prawa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.Galaz_prawa')),
            ],
        ),
        migrations.DeleteModel(
            name='Usluga',
        ),
    ]
