# Generated by Django 2.1.1 on 2018-09-03 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20180903_1839'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galaz_prawa',
            options={'verbose_name_plural': 'Usługi/Gałęzie prawa'},
        ),
        migrations.AlterModelOptions(
            name='swiadczone_uslugi',
            options={'ordering': ('nazwa_uslugi',), 'verbose_name_plural': 'Usługi/Świadczone usługi'},
        ),
    ]
