# Generated by Django 2.1.1 on 2018-09-05 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_auto_20180903_2028'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pracownik',
            new_name='Referencja',
        ),
    ]
