# Generated by Django 2.1.1 on 2018-09-05 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_auto_20180905_1005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referencja',
            options={'ordering': ('-publish',), 'verbose_name_plural': 'Referencje'},
        ),
        migrations.RenameField(
            model_name='referencja',
            old_name='email',
            new_name='nazwa',
        ),
        migrations.RemoveField(
            model_name='referencja',
            name='doswiadczenie',
        ),
        migrations.RemoveField(
            model_name='referencja',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='referencja',
            name='jezyki',
        ),
        migrations.RemoveField(
            model_name='referencja',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='referencja',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='referencja',
            name='wyksztalcenie',
        ),
    ]
