# Generated by Django 2.1.1 on 2018-09-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_auto_20180905_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='swiadczone_uslugi',
            name='galaz_prawa',
        ),
        migrations.RenameField(
            model_name='referencja',
            old_name='foto',
            new_name='logo',
        ),
        migrations.AddField(
            model_name='referencja',
            name='skan',
            field=models.ImageField(blank=True, upload_to='pracownik/%y/%m/%d'),
        ),
        migrations.DeleteModel(
            name='Galaz_prawa',
        ),
        migrations.DeleteModel(
            name='Swiadczone_uslugi',
        ),
    ]
